# $Id$

DEBUG=1

##########

RM=rm
AR=ar
CP=cp
LN=ln
CC=g++
TARGET=flexicom
UNAME:=$(shell uname)
MKDIR=mkdir
OUTDIR=out
TESTDIR=test

INCLUDEDIR=../include
MOC=moc
CFLAGS=-I$(INCLUDEDIR) -I$(INCLUDEDIR)/modules $(XFLAGS) `pkg-config --cflags gnuradio-core` -I `pkg-config --cflags gnuradio-uhd` -I `pkg-config --cflags QtGui` `pkg-config --cflags QtCore` `pkg-config --cflags uhd`
ifeq ($(UNAME),"Darwin")
	CFLAGS += -F/usr/local/qwt-6.0.0/lib -D_OSX
else
	CFLAGS += -I/usr/include/qwt
endif
LDFLAGS=-lboost_system -lm `pkg-config --libs gnuradio-core` `pkg-config --libs gnuradio-uhd` `pkg-config --libs gnuradio-audio` -lqwt `pkg-config --libs QtGui` \
	`pkg-config --libs uhd` `pkg-config --libs volk` `pkg-config --libs gnuradio-digital` `pkg-config --libs gnuradio-filter`
XFLAGS=-msse3 -mfpmath=sse -ffast-math -Wall -fno-strict-aliasing -g -pg -DLV_HAVE_GENERIC -O2

MAKEARGS=-f GNUMakefile 'CFLAGS=${CFLAGS}' \
		'CC=${CC}' \
		'LDFLAGS=${LDFLAGS}' \
		'INCLUDEDIR=${INCLUDEDIR}' \
		'RM=${RM}' \
		'AR=${AR}' \
		'CP=${CP}' \
		'DYNCOMP=${DYNCOMP}' \
		'MLDFLAGS=${MLDFLAGS}' \
		'LN=${LN}' \
		'MKDIR=${MKDIR}' \
		'OUTDIR=${OUTDIR}' \
		'TESTDIR=${TESTDIR}' \
		'MOC=${MOC}' 

all: build
build: 
	@if [ ! -r src/$(OUTDIR) ] ; then \
		$(MKDIR) src/$(OUTDIR); \
	fi
	cd src; ${MAKE} ${MAKEARGS} 'TARGET=${TARGET}' build; 
	
clean:
	$(RM) -f *~ *.so
	cd src; ${MAKE} ${MAKEARGS} clean;

frame_conversor: tools/frame_conversor.cc
	g++ tools/frame_conversor.cc -o frame_conversor $(CFLAGS)

test: do_test
do_test:
	cd src; ${MAKE} ${MAKEARGS} 'TARGET=${TARGET}' test; 
	./test_$(TARGET)
	