## $Id$

SOURCES=MainWindow.cc MainWindow_moc.cc LayoutFactory.cc
TESTS=test.cc test_example.cc 
LAYOUTS=BBN_PLCP.cc BBN_Slicer.cc BBN_DPSKDemod.cc Layout80211b.cc Rx80211b.cc \
				Layout80211b_moc.cc
LAYOUTS+=bb4b6bEnc.cc bb8b10bEnc.cc bbCCEnc.cc bbManchesterDec.cc bbManchesterEnc.cc \
					bbPHR_generation.cc bbPSDU_generation.cc bbRSEnc.cc bbVLC_Frame_Generator.cc \
					bbVLC_info_assembler.cc InterPunct.cc De2Bi.cc Bi2De.cc LayoutVLC.cc PHY_I_modulator.cc \
					PHY_II_modulator.cc RxVLC.cc TxVLC.cc vlc_convolutional_coding.cc \
					vlc_reed_solomon.cc LayoutVLC_moc.cc bbCCDec.cc TxTagger.cc Parser.cc\
					bb_bit_removal.cc bbVLC_Frame_Extractor.cc PHY_I_demodulator.cc bb_Header_cp.cc  \
					PHY_II_demodulator.cc bbRSDec.cc bb4b6bDec.cc bb8b10bDec.cc Interleaver.cc Puncture.cc \
					Correlator.cc Timing.cc DataSource.cc
TESTS+=test_CC.cc test_RLL.cc test_RS.cc test_VLCInterleaver.cc
MODULES=bbMatlab.cc QtBlock.cc QtBlock_moc.cc MSE.cc Tcp.cc Oversampler.cc Audio.cc
VPATH=layouts/80211b:layouts/VLC:modules:layouts/VLC/test:../test
CFLAGS_LAYOUTS=-Ilayouts/VLC -Ilayouts/80211b
OBJS=$(SOURCES:%.cc=$(OUTDIR)/%.o)
LAYOBJS=$(LAYOUTS:%.cc=$(OUTDIR)/%.o)
MODOBJS=$(MODULES:%.cc=$(OUTDIR)/%.o)
TESTOBJS=$(TESTS:%.cc=$(OUTDIR)/%.o)

INCLUDES=$(INCLUDEDIR)/LayoutFactory.h $(INCLUDEDIR)/MainWindow.h
MAKEARGS='CFLAGS=${CFLAGS}' \
		'CC=${CC}' \
		'LDFLAGS=${LDFLAGS}' \
		'INCLUDES=${INCLUDES}' \
		'INCLUDEDIR=${INCLUDEDIR}' \
		'RM=${RM}' \
		'AR=${AR}' \
		'CP=${CP}' \
		'MLDFLAGS=${MLDFLAGS}' \
		'LN=${LN}' \
		'TARGET=${TARGET}' \
		'MKDIR=${MKDIR}' \
		'OUTDIR=${OUTDIR}' \
		'TESTDIR=${TESTDIR}'

MAKE=make $(MAKEARGS)
all: build

build: $(OBJS) $(LAYOBJS) $(MODOBJS) $(OUTDIR)/main.o
	$(CC) $(CFLAGS) -o $(OUTDIR)/$(TARGET) $(OBJS) $(LAYOBJS) $(MODOBJS) $(OUTDIR)/main.o $(LDFLAGS) $(LIBS)
	@$(CP) $(OUTDIR)/$(TARGET) ../$(TARGET)

$(OUTDIR)/MainWindow.o: MainWindow.cc $(INCLUDES)
	$(MOC) $(INCLUDEDIR)/MainWindow.h -o MainWindow_moc.cc
	$(CC) $(CFLAGS) -D_REENTRANT -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -c MainWindow.cc -o $(OUTDIR)/MainWindow.o 
$(OUTDIR)/main.o: main.cc $(INCLUDES)
	$(CC) $(CFLAGS) -D_REENTRANT -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -c main.cc -o $(OUTDIR)/main.o 

$(OUTDIR)/Layout80211b.o: layouts/80211b/Layout80211b.cc $(INCLUDES)
	$(MOC) layouts/80211b/Layout80211b.h -o layouts/80211b/Layout80211b_moc.cc
	$(CC) $(CFLAGS) -D_REENTRANT -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -c layouts/80211b/Layout80211b.cc -o $(OUTDIR)/Layout80211b.o 
$(OUTDIR)/LayoutVLC.o: layouts/VLC/LayoutVLC.cc $(INCLUDES)
	$(MOC) layouts/VLC/LayoutVLC.h -o layouts/VLC/LayoutVLC_moc.cc
	$(CC) $(CFLAGS) -D_REENTRANT -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -c layouts/VLC/LayoutVLC.cc -o $(OUTDIR)/LayoutVLC.o 
$(OUTDIR)/QtBlock.o: modules/QtBlock.cc $(INCLUDES)
	$(MOC) $(INCLUDEDIR)/modules/QtBlock.h -o modules/QtBlock_moc.cc
	$(CC) $(CFLAGS) -D_REENTRANT -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -c modules/QtBlock.cc -o $(OUTDIR)/QtBlock.o 
	
$(OUTDIR)/%.o: %.cc $(INCLUDES)
	$(CC) $(CFLAGS) $(CFLAGS_LAYOUTS) -c $< -o $@

clean:
	$(RM) -f $(OUTDIR)/* $(OBJS)

test: $(OBJS) $(LAYOBJS) $(MODOBJS) $(TESTOBJS)
	$(CC) $(CFLAGS) -o $(OUTDIR)/test_$(TARGET) $(OBJS) $(LAYOBJS) $(MODOBJS) $(TESTOBJS) -lcppunit $(LDFLAGS) $(LIBS)
	@$(CP) $(OUTDIR)/test_$(TARGET) ../test_$(TARGET)
	